DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS ORDERS;
CREATE TABLE CUSTOMERS (CUSTOMER_ID INT PRIMARY KEY, CUSTOMER_NAME VARCHAR(255), ACC_NUMBER VARCHAR(255), CITY VARCHAR(255), CREDIT_LIMIT INT);
CREATE TABLE ORDERS (ORDER_ID INT PRIMARY KEY, ORD_VALUE NUMERIC(8,2), CUSTOMER_ID INT);
ALTER TABLE ORDERS
    ADD FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID);
