INSERT INTO CUSTOMER (CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES ('ACME Industries', 7600, 'AC001', 'London');
INSERT INTO CUSTOMER (CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES ('Smiths Corp', 1000, 'AC002', 'Dublin');
INSERT INTO CUSTOMER (CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES ('Phelps', 600, 'AC003', 'Birmingham');
INSERT INTO CUSTOMER (CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES ('A and C Ltd', 1000, 'AC004', 'London');
INSERT INTO CUSTOMER (CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES ('M and B Ltd', 1000, 'AC005', 'London');
INSERT INTO CUSTOMER (CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES ('Jones Products', 2000, 'AC006', 'London');