INSERT INTO CUSTOMER (ID, CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES (1, 'ACME Industries', 7600, 'AC001', 'London');
INSERT INTO CUSTOMER (ID, CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES (2, 'Smiths Corp', 1000, 'AC002', 'Dublin');
INSERT INTO CUSTOMER (ID, CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES (3, 'Phelps', 600, 'AC003', 'Birmingham');
INSERT INTO CUSTOMER (ID, CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES (4, 'M and B Ltd', 1000, 'AC004', 'London');