INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES (1, 'ACME Industries', 7600, 'AC001', 'London');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES (2, 'Smiths Corp', 1000, 'AC002', 'Dublin');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES (3, 'Phelps', 600, 'AC003', 'Birmingham');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES (4,'A and C Ltd', 1000, 'AC004', 'London');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES (5, 'M and B Ltd', 1000, 'AC005', 'London');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CREDIT_LIMIT, ACC_NUMBER, CITY) VALUES (6, 'Jones Products', 2000, 'AC006', 'Madrid');
INSERT INTO ORDERS (ORDER_ID, ORD_VALUE, CUSTOMER_ID) VALUES (1, 450.99, 3);